<?php

return [
    'title' => 'SOBRE NOSOTROS',
    'content' => '<h2 class="text-orange">Presentación</h2>
    <p>El Observatorio de la Juventud (Youth SIG) es una organización sin fines de lucro, fundada en setiembre de 2015 y adscrita a Internet Society (ISOC) como “Grupo Especial de Interés” (GES) desde el año 2016. Está conformada principalmente por jóvenes entre 18 y 25 años de diferentes países de Latinoamérica y el Caribe.</p>
    <p>Sus objetivos son los mismos que ISOC, pero haciendo énfasis en la capacitación de más jóvenes en los conocimientos del ecosistema y la gobernanza de Internet con el fin de incrementar su participación en estos espacios, la divulgación de la importancia de estos tópicos y la investigación académica.</p>
    <p>El Youth SIG busca tener un alcance global, para lo cual posee un programa de desarrollo para los próximos 2 años. Actualmente trabaja en proyectos regionales de creación de capacidades, difusión informativa y fomento de investigación hecha por jóvenes en los temas de gobernanza de Internet, ciberseguridad, derechos digitales, etc; todos esos proyectos son financiados por diferentes organizaciones como Internet Society y ICANN. </p>
    <p>Invitamos a todas las personas interesadas en apoyar las actividades de nuestra organización a ponerse en contacto con nosotros a través de nuestro correo institucional <a href="mailto:odjuventud@gmail.com">odjuventud@gmail.com</a>. Asimismo, si eres joven y deseas formar parte de nuestra organización, además de escribirnos puedes enviar una solicitud de membresía ingresando a tu cuenta en el sitio web: <a target="_blank" href="https://portal.isoc.org/home">https://portal.isoc.org/home</a> y enviando una aplicación al “Youth SIG” en la pestaña “Mis Capítulos”.</p>
    <h2 class="text-orange">Historia</h2>
    <p>El Observatorio de la Juventud fue una idea surgida dentro del contexto del programa Youth@IGF 2015, una iniciativa liderada por Internet Society y CGI.br que buscaba incrementar la participación de la juventud en los espacios de discusión de la gobernanza de Internet en Latinoamérica y el Caribe y que contó con la participación de 120 jóvenes de la región.</p>
    <p>No existe una fecha formal de constitución pues la idea fue evolucionando en el transcurso del pro grama, pero a finales de setiembre de 2015 ya se había decidido el nombre de la organización y sus principales objetivos. En esta etapa se preparó el primer gran proyecto colaborativo que tuvo como resultado la escritura y publicación de la “Declaración de la Juventud”, un documento escrito en español, portugués e inglés en el que los miembros del programa expresábamos nuestras preocupaciones y deseos con respecto a la participación de la juventud en los espacios de discusión de la gobernanza de Internet. Las copias de este documento fueron entregadas a distintas personalidades.</p>
    <p>La primera reunión presencial del Observatorio de la Juventud se realizó en Joao Pessoa (Brasil), durante el X Foro de Gobernanza de Internet, en donde se terminaron de definir los objetivos, se establecieron ciertas responsabilidades y se habilitaron canales de comunicación para emprender el proyecto de formalizar a la organización.</p>
    <p>Este proceso culminó en febrero de 2016 cuando recibimos la aprobación de ISOC y se nos otorgó el estatus de “Grupo Especial de Interés” (GES), lo que significa que desde esa fecha poseemos todos los derechos que tienen los capítulos de ISOC locales, entre los cuales está recibir financiamiento, asesoría y apoyo logístico para lograr nuestros objetivos, además de vernos respaldados por una organización de alcance global.</p>
    <p>Actualmente, el Youth SIG cuenta con más de 80 jóvenes de diferentes países que poseen la membresía y que participan activamente de las diferentes comisiones de trabajo. Asimismo, la organización tiene una estructura sólida y estatutos y reglamentos que permiten su crecimiento continuo. </p>
    <p>Invitamos a todas las personas interesadas en apoyar las actividades de nuestra organización a ponerse en contacto con nosotros a través de nuestro correo institucional <a href="mailto:odjuventud@gmail.com">odjuventud@gmail.com</a>. Asimismo, si eres joven y deseas formar parte de nuestra organización, además de escribirnos puedes enviar una solicitud de membresía ingresando a tu cuenta en el sitio web: <a target="_blank" href="https://portal.isoc.org/home">https://portal.isoc.org/home</a> y enviando una aplicación al “Youth SIG” en la pestaña “Mis Capítulos”.</p>
    <h2 class="text-orange">Estructura del Observatorio de la Juventud</h2>
    <p>Como todas las organizaciones adscritas a Internet Society (ISOC), el Observatorio de la Juventud cuenta con estatutos de constitución que han sido aprobados por sus miembros y que establecen la siguiente estructura administrativa: </p>
    <div class="row"><div class="col-sm-8 col-sm-offset-2"><img class="img-fluid" src="/images/aboutus/es/organograma.jpg"></div></div>
    <p>Todos los cargos son elegidos por voto universal de todos los miembros y duran 2 años sin la posibilidad de reelección inmediata para ocupar el mismo cargo. Los requisitos para ocupar cualquier cargo dentro de la organización son contar con una membresía activa, lo que implica cumplir los requisitos establecidos en los estatutos, ser mayor de edad en su país de origen y no haber sido destituido de un cargo en la organización con anterioridad. </p>
    <p>Actualmente, ya se han instalado las nuevas autoridades para el período 2016-2018. Para consultar a las autoridades elegidas y contactarlas o formar parte de sus grupos de trabajo, puedes consultar <a href="https://www.dropbox.com/sh/xbnpz25ze6dwyrr/AABLmBuxwa7nqUUoJqeuY9I1a?dl=0">aquí</a>.</p>
    <h2 class="text-orange">Misión y Visión del Observatorio de la Juventud</h2>
    <h3 class="text-orange">Visión</h3>
    <p>Usar el poder de Internet para crear capacidades en los jóvenes y así estimular su participación en el desarrollo del ecosistema y la gobernanza de Internet.</p>
    <h3 class="text-orange">Misión</h3>
    <p>Crear una plataforma que permita expandir el conocimiento sobre los principios de Internet y su gobernanza, además de fomentar un intercambio fluido y que acentúe la comunicación entre los jóvenes de la región Latinoamérica en torno a estos temas.</p>
    <p>Construir una identidad de la juventud, propendiendo a la apertura y difusión de sus ideas dentro del ecosistema de Internet, de tal forma que están sean incluidas en los debates locales y regionales.</p>
    <p>Empoderar a los jóvenes de la región para que puedan avanzar con su participación dentro de la Gobernanza de Internet y la difundan en sus comunidades. </p>
    <p>Generar capacidades en los jóvenes y transferir conocimientos para contar con herramientas y conocimientos sólidos para generar nuevas líneas de debate en los foros sobre la Gobernanza de Internet.</p>
    <p>Generar vínculos a nivel global a través de un diálogo y cooperación activa de las juventudes.</p>',
    'whereAreYouths' => '¿Dónde están los Jóvenes?',
];
