<?php

return [
    'title' => 'SOBRE NÓS',
    'content' => '<h2 class="text-orange">Apresentação</h2>
    <p>O Youth Observatory (Youth SIG) é uma organização sem fins lucrativos fundada em setembro de 2015 e anexado à Internet Society (ISOC) como "Grupo Especial de Interesse" desde 2016. Ele é formado principalmente por jovens entre 18 e 25 anos de diferentes países da América Latina e do Caribe.</p>
    <p>Seus objectivos são os mesmos da ISOC, mas com ênfase na formação de jovens no conhecimento do ecossistema e governança da Internet, a fim de aumentar a sua participação nesses espaços, a divulgação da importância destes temas e pesquisas acadêmicas.</p>
    <p>O Youth SIG busca ter um alcance global, para o qual tem um programa de desenvolvimento para os próximos 2 anos. Atualmente trabalha em projetos regionais de capacitação, difusão de informações e promoção da investigação por jovens sobre questões de governança da Internet, cibersegurança, direitos digitais, etc; todos estes projectos são financiados por diferentes organizações, como a Internet Society e a ICANN.</p>
    <p>Nós convidamos todas as pessoas interessadas em apoiar as atividades de nossa organização a contactar-nos através do nosso e-mail institucional <a href="mailto:odjuventud@gmail.com">odjuventud@gmail.com</a>. Além disso, se você é jovem e quer ser parte da nossa organização, você pode enviar um pedido de adesão, entrando em sua conta no site: <a target="_blank" href="https://portal.isoc.org/home">https://portal.isoc.org/home</a> e enviar um pedido ao "Youth SIG” na guia “Meus Capítulos".</p>
    <h2 class="text-orange">História</h2>
    <p>O Observário da Juventude foi um ideia surgida dentro do contexto do programa Youth@IGF 2015, uma iniciativa da Internet Society e CGI.br que buscava incrementar a participação da juventude nos espaços de discussão da Governança da Interne na América Latina e Caribe, e que contou com a participação de 120 jovens da região.</p>
    <p>Não existe uma data formal de criação pois a ideia foi evoluindo no decorrer do programa, porém, no final de setembro de 2015 já se havia decidido o nome da organização e seus principais objetivos. Nessa etapa foi preparado o primeiro grande projeto colaborativo que teve como resultado a escrita e publicação da “Declaração da Juventude”, um documento escrito em espanhol, português e inglês em que os membros do programa expressavam nossas preocupações e desejos em respeito a participação da juventude nos espaços de discussão da governança da Internet. As cópias desse documento foram entregues a distintas personalidades.</p>
    <p>A primeira reunião presencial do Observatório da Juventude se realizou em João Pessoa (Brasil), durante o X Fórum da Governança da Internet, onde terminou-se de definir os objetivos, se estabeleceram certas responsabilidades e se habilitaram canais de comunicação para empreender o projeto de formalizar a organização. </p>
    <p>Esse processo culminou em fevereiro de 2016, quando recebemos a aprovação da ISOC e nos foi outorgado o status de “Grupo Especial de Interesse” (GES), que significa que desde essa data possuímos todos os direitos que possuem os capítulos locais da ISOC, dentre os quais está receber financiamento, assessoria e apoio logístico para alcançar nossos objetivos, além de sermos respaldados por uma organização de alcance global. </p>
    <p>Atualmente, o Youth SIG conta com mais de 80 jovens de diferentes países que possuem a membresía e que participam ativamente das diferentes comissões de trabalho. Além disso, a organização tem uma estrutura sólida e estatutos e regulamentos que permitem seu crescimento contínuo.</p>
    <p>Convidamos a todas as pessoas interessadas em apoiar as atividades de nossa organização a contactar-nos através do nosso e-mail institucional odjuventud@gmail.com. Deste modo, se és jovem e deseja fazer parte de nossa organização, além de nos escrever, poderá enviar uma solicitação de membresia, criando uma conta no site: https://portal.isoc.org/home e enviando um uma aplicação ao "SIG Juventude" na guia "Meus capítulos".</p>
    <h2 class="text-orange">Estrutura do Observatório da Juventude</h2>
    <pComo todas as organizações inscritas na Internet Society (ISOC), o Observatório da Juventude conta com estatutos de constituição que foram aprovados pelos seus membros e que estabelecem a seguinte estrutura administrativa:></p>
    <div class="row"><div class="col-sm-8 col-sm-offset-2"><img class="img-fluid" src="/images/aboutus/en/organograma.jpg"></div></div>
    <p>Todos os cargos são eleitos por voto universal de todos os membros e duram 2 anos, sem a possibilidade de reeleição imediata para ocupar o mesmo cargo. Os requisitos para ocupar qualquer cargo dentro da organização são: contar com uma membresía ativa, o que implica cumprir os requisitos estabelecidos nos estatutos, ser maior de idade em seu país de origem e não haver sido destituído de um cargo na organização anteriormente.</p>
    <p>Atualmente, já foram eleitos as novas autoridades para o período 2016-2018. Para consultar as autoridades eleitas e contatá-las, ou fazer parte dos seus grupos de trabalho, você pode consultar <a href="https://www.dropbox.com/sh/xbnpz25ze6dwyrr/AABLmBuxwa7nqUUoJqeuY9I1a?dl=0">aqui</a>.</p>
    <h2 class="text-orange">Missão e Visão do Observatório da Juventude</h2>
    <h3 class="text-orange">Visão</h3>
    <p>Usar o poder da Internet para capacitação dos jovens e, assim, incentivar a sua participação no desenvolvimento do ecossistema e governança da Internet. </p>
    <h3 class="text-orange">Missão</h3>
    <p>Criar uma plataforma que permita expandir o conhecimento sobre os princípios da Internet e sua governança, além de fomentar um intercâmbio fluido que aumente a comunicação entre jovens da região da América Latina em torno desses temas.</p>
    <p>Construir uma identidade da juventude, fomentando a abertura e difusão de suas ideias dentro do ecossistema da Internet, de tal forma que estas sejam incluídas nos debates locais e regionais.</p>
    <p>Empoderar os jovens da região para que possam avançar com sua participação dentro da Governança da Internet e a difundir em suas comunidades. </p>
    <p>Gerar capacidades nos jovens e transferir conhecimentos para contar com ferramentas e conhecimentos sólidos para gerar novas linhas de debate nos fóruns sobre a Governança da Internet.</p>
    <p>Gerar vínculos a nível global através de um diálogo e cooperação ativa das juventudes.</p>',
    'whereAreYouths' => 'Onde estão os Jovens?!',
];
